#!/usr/bin/env python3
"""
Mortal Warcraft Item Classification Script

Classifies items from item_template into Mortal tiers and categories.
Assigns Mortal T1-T5 tiers based on quality, level, and source.

Usage:
    python3 classify_items.py [--input data/items_raw.csv] [--output item_tags.sql]
"""

import csv
import argparse
from pathlib import Path

# Tier assignment rules based on quality, level, and source
TIER_RULES = {
    # Endgame raid pieces -> T4-T5
    'T5': [
        lambda i: i.get('Quality', 0) == 4 and i.get('ItemLevel', 0) >= 245,  # Epic, ilvl 245+
        lambda i: i.get('Quality', 0) == 4 and 'raid' in str(i.get('description', '')).lower(),
    ],
    'T4': [
        lambda i: i.get('Quality', 0) == 4 and 200 <= i.get('ItemLevel', 0) < 245,  # Epic, ilvl 200-244
    ],
    # Heroic dungeon drops -> T3
    'T3': [
        lambda i: i.get('Quality', 0) == 3 and i.get('ItemLevel', 0) >= 200,  # Rare, ilvl 200+
        lambda i: i.get('Quality', 0) == 4 and 180 <= i.get('ItemLevel', 0) < 200,  # Epic, ilvl 180-199
    ],
    # Normal dungeons -> T2
    'T2': [
        lambda i: i.get('Quality', 0) == 3 and 150 <= i.get('ItemLevel', 0) < 200,  # Rare, ilvl 150-199
        lambda i: i.get('Quality', 0) == 2 and i.get('ItemLevel', 0) >= 150,  # Uncommon, ilvl 150+
    ],
    # Basic crafted/quest gear -> T1
    'T1': [
        lambda i: i.get('Quality', 0) == 2 and i.get('ItemLevel', 0) < 150,  # Uncommon, ilvl < 150
        lambda i: i.get('Quality', 0) == 1 and i.get('ItemLevel', 0) >= 100,  # Common, ilvl 100+
    ],
}

# Category mappings
CATEGORY_MAP = {
    'WEAPON': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],  # All weapon classes
    'ARMOR': [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],  # Armor classes
    'TRINKET': [23],  # Trinket
    'CONSUMABLE': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],  # Consumables
    'REAGENT': [6],  # Reagent
    'MOUNT_REINS': [15],  # Mount (if applicable)
}

def classify_item(item):
    """Classify a single item."""
    item_id = item.get('entry', 0)
    if not item_id:
        return None, None, None, None
    
    # Determine tier
    tier = None
    for tier_name, rules in TIER_RULES.items():
        for rule in rules:
            try:
                if rule(item):
                    tier = int(tier_name[1])  # Extract number from T1, T2, etc.
                    break
            except (KeyError, TypeError, ValueError):
                continue
        if tier:
            break
    
    # Determine category
    category = None
    class_id = item.get('class', 0)
    for cat, classes in CATEGORY_MAP.items():
        if class_id in classes:
            category = cat
            break
    
    # Determine usage policy
    usage_policy = 'ENABLED'
    quality = item.get('Quality', 0)
    
    # Complex trinkets might need conversion
    if category == 'TRINKET' and quality >= 3:
        usage_policy = 'CONVERT_TO_RUNE'  # Default, can be overridden
    
    # Mount items
    if 'mount' in str(item.get('name', '')).lower():
        category = 'MOUNT_REINS'
        usage_policy = 'ENABLED'
    
    notes = f"Auto-classified: Quality={quality}, Level={item.get('ItemLevel', 0)}"
    
    return tier, category, usage_policy, notes

def generate_sql(items, output_file):
    """Generate SQL INSERT statements for mortal_item_tags."""
    with open(output_file, 'w') as f:
        f.write("-- Item Tags - Generated by classify_items.py\n")
        f.write("-- This file can be imported into the world database\n\n")
        
        for item in items:
            tier, category, usage_policy, notes = classify_item(item)
            if tier is None and category is None:
                continue  # Skip items that don't match any rules
            
            item_id = item.get('entry', 0)
            if not item_id:
                continue
            
            # Build SQL
            tier_sql = f"{tier}" if tier is not None else "NULL"
            category_sql = f"'{category}'" if category else "NULL"
            usage_policy_sql = f"'{usage_policy}'" if usage_policy else "NULL"
            notes_escaped = notes.replace("'", "''") if notes else "NULL"
            notes_sql = f"'{notes_escaped}'" if notes else "NULL"
            
            f.write(f"INSERT INTO mortal_item_tags "
                   f"(item_id, mortal_tier, category, usage_policy, notes) "
                   f"VALUES ({item_id}, {tier_sql}, {category_sql}, {usage_policy_sql}, {notes_sql}) "
                   f"ON DUPLICATE KEY UPDATE "
                   f"mortal_tier = {tier_sql}, "
                   f"category = {category_sql}, "
                   f"usage_policy = {usage_policy_sql}, "
                   f"notes = {notes_sql};\n")
        
        # Update statistics
        f.write("\n-- Update statistics\n")
        f.write("UPDATE mortal_conversion_stats SET stat_value = "
               f"(SELECT COUNT(*) FROM mortal_item_tags), "
               f"last_updated = UNIX_TIMESTAMP() "
               f"WHERE stat_key = 'items_classified';\n")

def main():
    parser = argparse.ArgumentParser(description='Classify items for Mortal Warcraft conversion')
    parser.add_argument('--input', default='data/items_raw.csv',
                       help='Input CSV file (default: data/items_raw.csv)')
    parser.add_argument('--output', default='item_tags.sql',
                       help='Output SQL file (default: item_tags.sql)')
    
    args = parser.parse_args()
    
    # Load items from CSV
    items = []
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file {args.input} not found")
        print("Please export item_template from your database first")
        return 1
    
    with open(input_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        items = list(reader)
    
    print(f"Loaded {len(items)} items from {args.input}")
    
    # Generate SQL
    generate_sql(items, args.output)
    print(f"Generated SQL file: {args.output}")
    print(f"Run: mysql -u root -p world < {args.output}")
    
    return 0

if __name__ == '__main__':
    exit(main())

