#!/usr/bin/env python3
"""
Mortal Warcraft Quest Classification Script

Classifies quests from quest_template into Mortal conversion types:
- STORY_REWRITE: Important quest chains to rewrite as campaign acts
- CONTRACT_BOARD: Simple quests to convert to task board contracts
- CONTRACT_LOCAL: Escort/local quests to convert to local contracts
- FLAVOR: Flavor quests to keep as-is or lightly modify
- HUB_NARRATIVE: Hub narrative quests

Usage:
    python3 classify_quests.py [--input data/quests_raw.csv] [--output quest_tags.sql]
"""

import csv
import argparse
import re
from pathlib import Path

# Conversion type mappings based on quest characteristics
CONVERSION_RULES = {
    'STORY_REWRITE': [
        # Long chains, many prerequisites
        lambda q: q.get('PrevQuestId', 0) > 0 and q.get('NextQuestId', 0) > 0,
        # Class-specific quests
        lambda q: q.get('RequiredClasses', 0) != 0,
        # Level 80 quests (endgame content)
        lambda q: q.get('QuestLevel', 0) >= 75,
    ],
    'CONTRACT_BOARD': [
        # Simple kill/collect quests
        lambda q: q.get('Type', 0) in [1, 2, 3],  # KILL, COLLECT, etc.
        # No prerequisites
        lambda q: q.get('PrevQuestId', 0) == 0,
    ],
    'CONTRACT_LOCAL': [
        # Escort quests
        lambda q: q.get('Type', 0) == 11,  # ESCORT
        # Local area quests
        lambda q: q.get('Type', 0) == 13,  # LOCAL
    ],
    'FLAVOR': [
        # Low-level flavor quests
        lambda q: q.get('QuestLevel', 0) < 20,
        # Exploration quests
        lambda q: q.get('Type', 0) == 4,  # EXPLORE
    ],
}

def load_keystone_quests(keystone_file='data/keystone_quests.txt'):
    """Load manual override list of keystone quests."""
    keystones = set()
    keystone_path = Path(keystone_file)
    if keystone_path.exists():
        with open(keystone_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    try:
                        keystones.add(int(line))
                    except ValueError:
                        pass
    return keystones

def classify_quest(quest, keystone_quests):
    """Classify a single quest based on rules."""
    quest_id = quest.get('Id', 0)
    
    # Manual override: keystone quests are always STORY_REWRITE
    if quest_id in keystone_quests:
        return 'STORY_REWRITE', 'Keystone chain - manual override'
    
    # Apply conversion rules in priority order
    for conversion_type, rules in CONVERSION_RULES.items():
        for rule in rules:
            try:
                if rule(quest):
                    return conversion_type, f'Auto-classified by {conversion_type} rule'
            except (KeyError, TypeError):
                continue
    
    # Default: CONTRACT_BOARD for simple quests
    return 'CONTRACT_BOARD', 'Default classification'

def generate_sql(quests, keystone_quests, output_file):
    """Generate SQL INSERT statements for mortal_quest_conversion_map."""
    with open(output_file, 'w') as f:
        f.write("-- Quest Conversion Map - Generated by classify_quests.py\n")
        f.write("-- This file can be imported into the world database\n\n")
        
        for quest in quests:
            quest_id = quest.get('Id', 0)
            if not quest_id:
                continue
            
            conversion_type, notes = classify_quest(quest, keystone_quests)
            
            # Escape notes for SQL
            notes_escaped = notes.replace("'", "''")
            
            f.write(f"INSERT INTO mortal_quest_conversion_map "
                   f"(quest_id, conversion_type, notes) "
                   f"VALUES ({quest_id}, '{conversion_type}', '{notes_escaped}') "
                   f"ON DUPLICATE KEY UPDATE "
                   f"conversion_type = '{conversion_type}', "
                   f"notes = '{notes_escaped}';\n")
        
        # Update statistics
        f.write("\n-- Update statistics\n")
        f.write("UPDATE mortal_conversion_stats SET stat_value = "
               f"(SELECT COUNT(*) FROM mortal_quest_conversion_map), "
               f"last_updated = UNIX_TIMESTAMP() "
               f"WHERE stat_key = 'quests_classified';\n")

def main():
    parser = argparse.ArgumentParser(description='Classify quests for Mortal Warcraft conversion')
    parser.add_argument('--input', default='data/quests_raw.csv',
                       help='Input CSV file (default: data/quests_raw.csv)')
    parser.add_argument('--output', default='quest_tags.sql',
                       help='Output SQL file (default: quest_tags.sql)')
    parser.add_argument('--keystones', default='data/keystone_quests.txt',
                       help='Keystone quests override file (default: data/keystone_quests.txt)')
    
    args = parser.parse_args()
    
    # Load keystone quests
    keystone_quests = load_keystone_quests(args.keystones)
    print(f"Loaded {len(keystone_quests)} keystone quests from {args.keystones}")
    
    # Load quests from CSV
    quests = []
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file {args.input} not found")
        print("Please export quest_template from your database first")
        return 1
    
    with open(input_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        quests = list(reader)
    
    print(f"Loaded {len(quests)} quests from {args.input}")
    
    # Generate SQL
    generate_sql(quests, keystone_quests, args.output)
    print(f"Generated SQL file: {args.output}")
    print(f"Run: mysql -u root -p world < {args.output}")
    
    return 0

if __name__ == '__main__':
    exit(main())

