#!/usr/bin/env python3
"""
Mortal Warcraft NPC Classification Script

Classifies NPCs from creature_template into roles and scaling profiles.

Usage:
    python3 classify_npcs.py [--input data/npcs_raw.csv] [--output npc_tags.sql]
"""

import csv
import argparse
from pathlib import Path

# Role assignment rules
ROLE_RULES = {
    'WORLD_BOSS': [
        lambda n: n.get('rank', 0) == 3,  # Boss rank
        lambda n: n.get('type_flags', 0) & 0x00000001,  # Boss flag
    ],
    'BOSS': [
        lambda n: n.get('rank', 0) == 3 and n.get('level', 0) >= 80,
    ],
    'MID_ELITE': [
        lambda n: n.get('rank', 0) == 2 and n.get('level', 0) >= 60,
    ],
    'WEAK_MOB': [
        lambda n: n.get('rank', 0) == 0 and n.get('level', 0) < 60,
    ],
    'GUARD': [
        lambda n: 'guard' in str(n.get('name', '')).lower(),
        lambda n: n.get('type', 0) == 7,  # Humanoid guard type
    ],
    'TRADER': [
        lambda n: n.get('npcflag', 0) & 0x00000002,  # Vendor flag
        lambda n: 'vendor' in str(n.get('name', '')).lower(),
    ],
}

# Scaling profile assignment
SCALING_PROFILES = {
    'FRONTIER_ELITE': lambda n: n.get('rank', 0) >= 2 and n.get('level', 0) >= 70,
    'PUBLIC_DUNGEON': lambda n: n.get('rank', 0) >= 1,
    'STRONGHOLD_DEFENDER': lambda n: 'guard' in str(n.get('name', '')).lower() or n.get('type', 0) == 7,
}

def classify_npc(npc):
    """Classify a single NPC."""
    entry = npc.get('entry', 0)
    if not entry:
        return None, None, None, None
    
    # Determine role
    role = None
    for role_name, rules in ROLE_RULES.items():
        for rule in rules:
            try:
                if rule(npc):
                    role = role_name
                    break
            except (KeyError, TypeError, ValueError):
                continue
        if role:
            break
    
    # Determine scaling profile
    scaling_profile = None
    for profile_name, rule in SCALING_PROFILES.items():
        try:
            if rule(npc):
                scaling_profile = profile_name
                break
        except (KeyError, TypeError, ValueError):
            continue
    
    notes = f"Auto-classified: Rank={npc.get('rank', 0)}, Level={npc.get('level', 0)}"
    
    return role, scaling_profile, notes

def generate_sql(npcs, output_file):
    """Generate SQL INSERT statements for mortal_npc_tags."""
    with open(output_file, 'w') as f:
        f.write("-- NPC Tags - Generated by classify_npcs.py\n")
        f.write("-- This file can be imported into the world database\n\n")
        
        for npc in npcs:
            role, scaling_profile, notes = classify_npc(npc)
            if role is None and scaling_profile is None:
                continue  # Skip NPCs that don't match any rules
            
            entry = npc.get('entry', 0)
            if not entry:
                continue
            
            # Build SQL
            role_sql = f"'{role}'" if role else "NULL"
            scaling_profile_sql = f"'{scaling_profile}'" if scaling_profile else "NULL"
            notes_escaped = notes.replace("'", "''") if notes else "NULL"
            notes_sql = f"'{notes_escaped}'" if notes else "NULL"
            
            f.write(f"INSERT INTO mortal_npc_tags "
                   f"(entry, role, scaling_profile, notes) "
                   f"VALUES ({entry}, {role_sql}, {scaling_profile_sql}, {notes_sql}) "
                   f"ON DUPLICATE KEY UPDATE "
                   f"role = {role_sql}, "
                   f"scaling_profile = {scaling_profile_sql}, "
                   f"notes = {notes_sql};\n")
        
        # Update statistics
        f.write("\n-- Update statistics\n")
        f.write("UPDATE mortal_conversion_stats SET stat_value = "
               f"(SELECT COUNT(*) FROM mortal_npc_tags), "
               f"last_updated = UNIX_TIMESTAMP() "
               f"WHERE stat_key = 'npcs_classified';\n")

def main():
    parser = argparse.ArgumentParser(description='Classify NPCs for Mortal Warcraft conversion')
    parser.add_argument('--input', default='data/npcs_raw.csv',
                       help='Input CSV file (default: data/npcs_raw.csv)')
    parser.add_argument('--output', default='npc_tags.sql',
                       help='Output SQL file (default: npc_tags.sql)')
    
    args = parser.parse_args()
    
    # Load NPCs from CSV
    npcs = []
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file {args.input} not found")
        print("Please export creature_template from your database first")
        return 1
    
    with open(input_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        npcs = list(reader)
    
    print(f"Loaded {len(npcs)} NPCs from {args.input}")
    
    # Generate SQL
    generate_sql(npcs, args.output)
    print(f"Generated SQL file: {args.output}")
    print(f"Run: mysql -u root -p world < {args.output}")
    
    return 0

if __name__ == '__main__':
    exit(main())

